name: "Prod deploy"

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest

    env:
      ALGOLIA_API_KEY: ${{ vars.ALGOLIA_API_KEY }}
      ALGOLIA_APP_ID: ${{ vars.ALGOLIA_APP_ID }}
      GOOGLE_ANALYTICS_ID: ${{ vars.GOOGLE_ANALYTICS_ID }}

    steps:
      - uses: actions/checkout@v3
      - uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_DEPLOY_MESSAGE: "Prod deploy v${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: true
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
